name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    shell: bash
    working-directory: ./front

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: ./front/package-lock.json

      - name: npm-install
        run: npm ci

      - name: Next.js Build
        run:  npm run build

      - uses: actions/checkout@v3
      - name: Rust Build
        run: cd .. && cargo build --release

      - name: make dir
        run: cd .. && mkdir app

      - name: copy
        run: mv ./target/release/axum-next-test ./app/axum && ./static ./app/static

      - uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "axum-next-test"
          heroku_email: "inomatama08@gmail.com"
          buildpack: "https://github.com/ph3nx/heroku-binary-buildpack.git"
          appdir: "./app"
          procfile: "web: ./axum"
