name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: ./front/package-lock.json
          working-directory: ./front

      - name: npm-install
        run: npm ci
        working-directory: ./front

      - name: Next.js Build
        run:  npm run build
        working-directory: ./front

      - name: Rust Build
        run: cargo build --release

      - name: make dir
        run: mkdir app

      - name: copy rust file
        run: mv ./target/release/axum-next-test ./app/axum

      - name: copy next file
        run: mv ./front/out ./app/front/out

      - uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "axum-next-test"
          heroku_email: "inomatama08@gmail.com"
          buildpack: "https://github.com/ph3nx/heroku-binary-buildpack.git"
          appdir: "./app"
          procfile: "web: ./axum"
